#!/usr/bin/env bash

# ==============================================
# ~/.macos
# macOS Sequoia (15.x)
# Compatibility-updated version for modern macOS
# ==============================================
# System Settings (formerly System Preferences)
#    1. Set hostname
#    2. Date & Time
#    3. Application Layer Firewall
#    4. Login window
# User Preferences
# ==============================================

# Check hostname argument
if [ "$#" -ne 1 ]; then
  echo "Usage: $0 enter_hostname >" >&2
  exit 1
fi

# Close any open System Settings panes
osascript -e 'tell application "System Settings" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until this script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# ==============================================
# Start: System Settings
# ==============================================

# ==============================================
# System Settings: Set hostname
# ==============================================

sudo scutil --set ComputerName $1
sudo scutil --set HostName $1
sudo scutil --set LocalHostName $1
# sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string $1

# ==============================================
# System Settings: Date & Time
# ==============================================

sudo /usr/sbin/systemsetup -settimezone "Africa/Johannesburg" 2>&-
sudo /usr/sbin/systemsetup -setnetworktimeserver "time.apple.com" 2>&-
sudo /usr/sbin/systemsetup -setusingnetworktime on 2>&-
sudo defaults write /Library/Preferences/com.apple.timezone.auto Active -bool false

# ==============================================
# System Settings: Application Layer Firewall
# ==============================================

# Enable ALF
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on

# Allow downloaded signed apps
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setallowsignedapp on

# Allow signed apps
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setallowsigned on

# Disable stealth mode
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setstealthmode on

# ==============================================
# System Settings: Login window
# ==============================================

# Show shut down etc. buttons
sudo defaults write /Library/Preferences/com.apple.loginwindow PowerOffDisabled -bool false

# Don't show any password hints
sudo defaults write /Library/Preferences/com.apple.loginwindow RetriesUntilHint -int 0

# Hide users with UID under 500
sudo defaults write /Library/Preferences/com.apple.loginwindow Hide500Users -bool YES

# ==============================================
# End: System Settings
# ==============================================

# ==============================================
# Start: User Preferences
# ==============================================
# ==============================================
# User Preferences: General
# ==============================================
echo "User Preferences: General panel"

# Sidebar icon size: Small
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 1
# Possible values: 1 = Small, 2 = Medium, 3 = Large

# Always show scrollbars
defaults write NSGlobalDomain AppleShowScrollBars -string "WhenScrolling"
# Possible values: 'WhenScrolling', 'Automatic', 'Always'

# Don't restore windows when quitting or re-opening apps
defaults write NSGlobalDomain NSQuitAlwaysKeepsWindows -bool false

# ==============================================
# User Preferences: Desktop & Screen Saver
# ==============================================
echo "User Preferences: Desktop & Screen Saver"

# Hot corners:  bottom left = start screen saver
defaults write com.apple.dock "wvous-bl-corner" -int 5
defaults write com.apple.dock "wvous-bl-modifier" -int 0

# ==============================================
# User Preferences: Dock
# ==============================================
echo "User Preferences: Dock"

# Set size of dock
defaults write com.apple.dock tilesize -int 32

# Enable magnification
defaults write com.apple.dock magnification -bool true

# Set magnification in dock
defaults write com.apple.dock largesize -int 64

# Set orientation of dock
defaults write com.apple.dock orientation -string bottom

# Show hidden applications
defaults write com.apple.dock showhidden -bool true

# Animate application launch
defaults write com.apple.dock launchanim -bool true

# Show indicators for open applications
defaults write com.apple.dock show-process-indicators -bool true

# Don't show recent applications in Dock
defaults write com.apple.dock show-recents -bool false

# ==============================================
# User Preferences: Mission Control
# ==============================================
echo "User Preferences: Mission Control"

# Disbale rearranging Spaces based on recent use
defaults write com.apple.dock mru-spaces -bool false

# ==============================================
# User Preferences: Language & Region
# ==============================================
echo "User Preferences: Language & Region"

# Set locale
defaults write NSGlobalDomain AppleLocale -string "en_ZA"

# ==============================================
# User Preferences: Keyboard
# ==============================================
echo "User Preferences: Keyboard"

# Disable automatic capitalization
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

# Disable smart dashes
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# Disable automatic period substitution
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

# Disable smart quotes
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

# Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# ==============================================
# User Preferences: Trackpad
# ==============================================
echo "User Preferences: Trackpad preferences"

# Set trackpad tracking speed
defaults write -g com.apple.trackpad.scaling 3

# ==============================================
# User Preferences: NSGlobalDomain settings
# ==============================================
echo "User Preferences: NSGlobalDomain preferences"

# Save to disk (not to iCloud) by default
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Expand print panel by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

# ==============================================
# User Preferences: Menu Bar
# ==============================================
echo "User Preferences: Menu Bar preferences"

# Menu Bar Date Format
defaults write com.apple.menuextra.clock "DateFormat" "EEE d MMM  HH:mm:ss"

# Show battery percentage in menu bar
defaults write com.apple.controlcenter "NSStatusItem Visible Battery" -bool true
defaults write ~/Library/Preferences/ByHost/com.apple.controlcenter.plist BatteryShowPercentage -bool true

# ==============================================
# User Preferences: App: Finder
# ==============================================
echo "User Preferences: Finder preferences"

# Show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# Show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Show tab bar
defaults write com.apple.finder ShowTabView -bool true

# Display full POSIX path as Finder window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# New window points to home
defaults write com.apple.finder NewWindowTarget -string "PfHm"
## defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/Desktop/"

# Show icons for hard drives, servers, and removable media on the desktop
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowMountedServersOnDesktop -bool false
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool false

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Finder: allow text selection in Quick Look
defaults write com.apple.finder QLEnableTextSelection -bool true

# When performing a search, search the current folder by default
# defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Avoid creating .DS_Store files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Use column view
defaults write com.apple.finder FXPreferredViewStyle -string "clmv"

# ==============================================
# User Preferences: Screen Capture
# ==============================================
echo "User Preferences: Screenshots preferences"

# Save screenshots to the custom directory
mkdir -p "${HOME}/Documents/screenshots"
defaults write com.apple.screencapture location -string "${HOME}/Documents/screenshots"

# Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
defaults write com.apple.screencapture type -string "png"

# Disable shadow in screenshots
defaults write com.apple.screencapture disable-shadow -bool true

# Include date in screenshot filename
defaults write com.apple.screencapture include-date -bool true

# ==============================================
# User Preferences: App: TextEdit
# ==============================================
echo "User Preferences: TextEdit preferences"

# Use plain text mode for new documents
defaults write com.apple.TextEdit RichText -int 0

# Open and save files as UTF-8
defaults write com.apple.TextEdit PlainTextEncoding -int 4
defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4

# ==============================================
# User Preferences: App: Activity Monitor
# ==============================================
echo "User Preferences: Activity Monitor preferences"

# Show the main window when launching
defaults write com.apple.ActivityMonitor OpenMainWindow -bool true

# Show all processes
defaults write com.apple.ActivityMonitor ShowCategory -int 0

# ==============================================
# Kill affected applications
# ==============================================

function killallApps() {
    killall "Finder" > /dev/null 2>&1
    killall "SystemUIServer" > /dev/null 2>&1
    killall "Dock" > /dev/null 2>&1

    appsToKill=(
    "Dashboard"
    "System Settings"
    )

    for app in "${appsToKill[@]}"
    do
        killall "${app}" > /dev/null 2>&1
        if [[ $? -eq 0 ]]; then
            # We just killed an app so restart it
            open -a "${app}"
        fi
    done

    echo "Note that some of these changes require a logout/restart to take effect."
}

printf "Restart the affected applications? (y/n): "
read killallReply
if [[ $killallReply =~ ^[Yy]$ ]]; then
    killallApps
fi

exit 0

# ==============================================
# End: User Preferences
# ==============================================
