#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until this script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Update Homebrew
brew update

# Upgrade installed Homebrew formulae
brew upgrade

# Homebrew default install location
BREW_PREFIX=$(brew --prefix)

# ==============================================
# Command line apps
# ==============================================

# GNU software
# https://gnu.org/software
# https://www.gnu.org/manual/blurbs.html
# most utilities are 'g'-prefixed
brew install findutils
brew install gawk
brew install gnu-sed
brew install gnu-tar
brew install grep
brew install gzip

# Useful command-line binaries
brew install certbot
brew install direnv
brew install dockutil
brew install git
brew install jo
brew install jq
brew install nmap
brew install p7zip
# brew install pyenv
# brew install pyenv-virtualenv
brew install rsync
brew install screen
brew install ssh-copy-id
brew install tfenv
brew install tree
brew install unar
brew install uv
brew install watch
brew install wget
brew install xz
brew install yt-dlp
brew install zstd

# Remove outdated version from Cellar
brew cleanup

# ==============================================
# macOS apps
# ==============================================

brew install --cask 1password
# brew install --cask affinity-designer
brew install --cask box-drive
brew install --cask citrix-workspace
brew install --cask google-chrome
brew install --cask iterm2
brew install --cask microsoft-auto-update
# brew install --cask microsoft-office
brew install --cask microsoft-teams
brew install --cask orbstack
brew install --cask slack
brew install --cask sublime-text
brew install --cask telegram
brew install --cask the-unarchiver
brew install --cask visual-studio-code
brew install --cask windows-app
brew install --cask zoom

# ==============================================
# Fonts
# ==============================================

brew install --cask font-fira-code
brew install --cask font-jetbrains-mono

# ==============================================
# done
# ==============================================
