#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until this script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# vars to use script and set current logged in user dock
loggedInUser=$(ls -l /dev/console | awk '{print $3}')
LoggedInUserHome="/Users/$loggedInUser"
UserPlist=$LoggedInUserHome/Library/Preferences/com.apple.dock.plist

################################################################################
# Use Dockutil to Modify Logged-In User's Dock
################################################################################

echo "------------------------------------------------------------------------"
echo "Current logged-in user: $loggedInUser"
echo "------------------------------------------------------------------------"
echo "Removing all Items from the Logged-In User's Dock..."
sudo -u $loggedInUser dockutil --remove all --no-restart $UserPlist
echo "Creating New Dock..."
sudo -u $loggedInUser dockutil --add "/Applications/Finder.app" --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "/Applications/Launchpad.app" --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "/Applications/System Settings.app" --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "/Applications/Music.app" --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "" --type spacer --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "/Applications/Preview.app" --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "/Applications/Notes.app" --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "" --type spacer --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "/Applications/1Password.app" --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "/Applications/ExpressVPN.app" --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "" --type spacer --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "/Applications/Safari.app" --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "/Applications/Google Chrome.app" --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "" --type spacer --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "/Applications/Microsoft Outlook.app" --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "/Applications/Microsoft Teams.app" --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "/Applications/Telegram.app" --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "/Applications/Slack.app" --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "/Applications/zoom.us.app" --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "" --type spacer --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "/Applications/Visual Studio Code.app" --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "/Applications/Sublime Text.app" --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "/Applications/iTerm.app" --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "" --type spacer --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "/Applications/Windows.app" --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "/Applications/OrbStack.app" --no-restart $UserPlist
sudo -u $loggedInUser dockutil --add "~/Downloads" --section others --view list --display folder --no-restart $UserPlist
echo "Restarting Dock..."
sudo -u $loggedInUser killall Dock

exit 0
